### ISSUE TITLE
ONNX conversion in notebook not working

### ISSUE THREAD

**Issue by marcelfranke** [Azure-Samples/Synapse#74]
The onnx conversion in the notebook tutorial-predict-nyc-taxi-tips-onnx.ipynb is not working. I'll get the error "ValueError: You passed in an iterable attribute but I cannot figure out its applicable type."

**Comment by rohrerb** [comment]
> The onnx conversion in the notebook tutorial-predict-nyc-taxi-tips-onnx.ipynb is not working. I'll get the error "ValueError: You passed in an iterable attribute but I cannot figure out its applicable type."

Same here!  @marcelfranke  did you find the fix?

**Comment by rohrerb** [comment]
> The onnx conversion in the notebook tutorial-predict-nyc-taxi-tips-onnx.ipynb is not working. I'll get the error "ValueError: You passed in an iterable attribute but I cannot figure out its applicable type."

Hi @marcelfranke,  comment out the first two lines and re-run.

```
%pip list
%pip install scikit-learn==0.20.3
```

### Please note that for successful conversion to ONNX, this notebook requires using Scikit-learn version 0.20.3. Run the first cell to list the packages installed and check your sklearn version. Uncomment the pip install command to install the correct version

%pip install scikit-learn==0.20.3

**Comment by marcelfranke** [comment]
Works, sorry my fault. I should better read the documentation.
